# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 51666751c2f2064534f4f904e8fc14e7f1c5b32d469fbef75bbca18d4f0d5c01c156790a14de16a148c035ad2ce29f2978e9f5ae1938c32991b67f0386db001f

test:
  secret_key_base: c29a1f44ebb45f2dde011fedc19b0aba1427e13aa4e99db895cb21c872b174d2230894eacc777db39ed920bfb1498a34b254b45428a2857b388f55abb576bcae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
